config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#landing"

  resources :listings do
    resources :comments, only: [:new, :create, :destroy]
  end 
  resources :tradesmen
  resources :profiles do 
    member do
      get "profile_listings"
      end
      resources :reviews, only: [:new, :create, :destroy]
    end
    
  resources :payments, only: [:create]
  get "/payments/success", to: "payments#success"
  get "/payments/cancel", to: "payments#cancel"
  post "/payments/webhook", to: "payments#webhook"

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  #this is where the relations with other models are established
  belongs_to :user
  has_many :reviews

  #this enum essentially allows me to attach string words like welding to numbers in a nice drop down menu!
  enum skills: {
    " ": 0,
    "Carpentry": 1,
    "Welding": 2,
    "Landscaping": 3,
    "Plumbing": 4,
    "Electrician": 5,
  }

  #validation that restricts how inputs can be filled in
  validates :name, length: {minimum: 2, too_short: "%{count} is the minimum number of characters"}
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:show, :edit, :update, :profile_listings]
  before_action :authorize_user, only: [:edit, :update, :profile_listings]

  def index
    @profiles = Profile.all
  end 
  
  def show
    @review = Review.new
  end 

  def profile_listings
  @listings = current_user.listings
  end 

  def new
    @profile = Profile.new
  end 

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    if @profile.save 
      redirect_to listings_path
    else
      render :new
    end 
  end 

  def edit
    @profile = Profile.find(params[:id])
  end 

  def update
    if @profile.update(profile_params)
      redirect_to profile_path
    else 
      render :edit
    end 
  end

  private 

  #this is an example of authorizations that prevents people accessing profiles exception in a situation I have allowed through the comments.
  def authorize_user
    unless current_user.id == @profile.user_id
      flash[:unauthorized] = "Not authorized"
      redirect_to listings_path
    end 
  end

  #this sets a profile where it is relevant, such as for the show action above, and will happen before the show action (for example) executes due to the before_action
  def set_profile
    id = params[:id]
    @profile = Profile.find(id)
  end 

  #this sets the allowed parameters that users can enter ino the application in conjunction with its before_action
  def profile_params
    params.require(:profile).permit(:name, :description, :place_of_business, :about_me, :skills)
  end 

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_edit_profile_form.html.erb
<%#this is the edit form field that users can access through the edit function. note the additional fields so users can tailor their profile to provide trade info.%>
<div>
  <% if @profile.errors.any? %>
    <%= @profile.errors.full_messages %>
  <% end %>
</div>


<%= form_with model: @profile, local: true do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, length: {minimum: 3}, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= form.label :user_description %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :place_of_business %>
    <%= form.text_field :place_of_business, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :about_me %>
    <%= form.text_field :about_me, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :skills_list %>
    <%= form.select :skills, options_for_select(Profile.skills.keys), class: 'form-control checkbox' %>
  </div>

  <div class="form-group">
    <%= form.submit id: "submit" %>
  </div>
<% end %>
</div>

app/views/profiles/_new_user_profile_form.html.erb
<%# this is the form to create a profile upon user creation, note does not have all the fields the edit form has %>

<%= form_with model: @profile, local: true do |form| %>
  <div class="form-group">
    <strong><%= form.label :name %>:</strong>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <strong><%= form.label :user_description %>:</strong>
    <p>What are you using the site for? to hire tradesman? to find work? both!?</p>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit id: "submit" %>
  </div>
<% end %>
</div>

app/views/profiles/_profile_form.html.erb
Hi <%= current_user.username %>!

<div>
<%= form_with model: @profile, local: true do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :place_of_business %>
    <%= form.text_field :place_of_business, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :about_me %>
    <%= form.text_field :about_me, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :Skills %>
    <%= form.select :skills, options_for_select(Profile.skills.keys), class: 'form-control checkbox' %>
  </div>

  <div class="form-group">
    <%= form.submit id: "submit" %>
  </div>
<% end %>
</div>

app/views/profiles/edit.html.erb
<h1>Edit Profile</h1>
<%#note this renders ONLY the edit profile form, this is because it it serves a separate function to the edit form%>
<p><%= render 'edit_profile_form', profile: @profile %></p>

app/views/profiles/index.html.erb
<h1>profile index</h1>

<%#  this just renders a list of user profiles, allowing people to scout out potential tradesman %>
<% @profiles.each do |profile| %>
  <p>Name: <%= profile.name %></p>
  <p>Description: <%= profile.description %></p>
  <p>Place of business: <%= profile.place_of_business %></p>
  <p>About me: <%= profile.about_me %> </p>
<% end %>

app/views/profiles/new.html.erb
<%#this is for when users first sign up, they will be messaged and then as they don't have a profile they will have the new user profile form rendered%>
<h1>Make your profile!</h1>

<p>Hi <%= current_user.username %>!</p>

<% if current_user.profile.nil? %>
  <p>We're very excited to have you join, just a few more steps and you'll be able to post listings!</p>
  <p><strong>Note</strong> that if you are planning on registering as a tradesperson, there are some additional fields you can fill out when <strong>editing</strong> your profile in the 'Your Profile' tab, to give users more information about you, and your work! </p>
<% end %>

<p><%= render "new_user_profile_form", listing: @profile %></p>

app/views/profiles/profile_listings.html.erb
<%# simple ruby loop to just print out the listings associated with a profile %>
<h1>your listings:</h1>

<% @listings.each do |listing|%>
  <%= link_to listing.name, listing %>
<% end %>

app/views/profiles/show.html.erb
<h1>Profile:</h1>

<%# this renders your profile information where it is filled in, otherwise it will not appear until a user edits it to not be blank%>
<div class="card profile-info">
  <p><strong>Name:</strong> <%= @profile.name %> </p>
  <p><strong>User Description:</strong> <%= @profile.description %></p>

  <% unless @profile.about_me.blank? %>
    <p><strong>About me:</strong> <%= @profile.about_me %></p>
  <% end %>

  <% unless @profile.place_of_business.blank? %>
    <p><strong>Place of Business:</strong> <%= @profile.place_of_business%></p>
  <% end %>

  <% unless @profile.skills.blank? %>
    <p><strong>Primary area of work:</strong> <%= @profile.skills %></p>
  <% end %>

  <% if user_signed_in? && current_user.profile == @profile %>
    <%= link_to "edit profile", edit_profile_path(current_user.profile.id) %> 
    <%= link_to "your listings", profile_listings_profile_path(@profile) %>
  <% end %>
</div>

<%#Users may add reviews here%>
<% unless current_user.profile.id == @profile.id %>
<div class="card reviews-container">
  <div class="create-review">
    <p><strong>Add a review:</strong></p>
    <%= render partial: 'reviews/review_form', locals: {profile: @profile, review: @review} %>
  </div>
</div>
<% end %>

  <%# reviews will be listed here%>
  <div class="render-reviews">
    <%= render partial: 'reviews/review', locals: {reviews: @profile.reviews} %>
  </div>
</div>