config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#landing"

  resources :listings do
    resources :comments, only: [:new, :create, :destroy]
  end 
  resources :tradesmen
  resources :profiles do 
    member do
      get "profile_listings"
      end
      resources :reviews, only: [:new, :create, :destroy]
    end
    
  resources :payments, only: [:create]
  get "/payments/success", to: "payments#success"
  get "/payments/cancel", to: "payments#cancel"
  post "/payments/webhook", to: "payments#webhook"

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  include Searchable

  #this is where the relations with other models are established
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :picture, dependent: :destroy

  #validations that restrict how inputs can be filled in
  validates :price, numericality: { only_integer: true }
  validates :description, length: { in: 10..500 }
  validates :name, length: { in: 2..150 }

  #these are the scopes form my three search bards, i.e. the name of the listing is like what is searched for, or the price is related to the ranges specified in 16 and 17
  scope :search_by_listing, -> (listing) { Listing.where('name ILIKE ?', "%#{listing}%") } 
  scope :search_by_min_price, -> (price) { where price: price.to_i..100000 }
  scope :search_by_max_price, -> (price) {where price: 0..price.to_i}
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  #this creates the index where all listings can be displayed concurrently, also note that line 8 refers to the search bar, essentially stating that if a search
  #has been made, rails will filter or search_by the parameters of that search (search_params)
  def index
    if params[:search].present?
      @listings = Listing.search_by(search_params)
    else
      @listings = Listing.all
    end
  end 

  #this is empty as rails will render the show page implictly
  def show
  end 

  #a new instance of listing begins here and then moves to create
  def new
    @listing = Listing.new
  end 

  #this is where a new listing instance will transfer to, it sets the user relation to that instance as the currently logged in user, then will and redirect to the 
  #listing. If it fails it will re-render the new listing view. 
  def create
    @listing = current_user.listings.new(listing_params)
    @listing.user = current_user
    if @listing.save
      ListingMailer.send_listing_new_mail(current_user).deliver
      redirect_to @listing, notice: 'Listing successfully created!'
    else
      render :new
    end 
  end
  
  def edit
    @listing = Listing.find(params[:id])
  end 

  def update
    @listing.update(listing_params)
    redirect_to listings_path
  end

  def destroy
    @listing.destroy
    redirect_to listings_path
  end 


  private

  def authorize_user
    unless current_user.id == @listing.user_id
      flash[:unauthorized] = "Not authorized"
      redirect_to listings_path
    end 
  end

  def set_listing
    id = params[:id]
    @listing = Listing.find(id)
  end 

  def listing_params
    params.require(:listing).permit(:name, :price, :available, :description, :picture)
  end 

  #this is also related to the search function
  def search_params
    params.require(:search).permit(:listing, :min_price, :max_price)
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%# this is form to make a listing, and contains the inputs that users are permitted to add through the controller, as well as some bootstrap styling elements%>
<div>
  <%= form_with model: @listing, local: true do |form| %>
  <div class="form-group">
    <%= form.label :listing_title %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :estimated_budget %>:
    <%= form.number_field :price, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :currently_available? %>
    <%= form.check_box :available %>
  </div>
  <div class="form-group">
    <%= form.label :description_of_job %>:
    <%= form.text_field :description, class: 'form-control' %>

    <%= form. label :picture %>
    <%= form.file_field :picture, accept: 'image/png, image/jpg, image/jpeg' %>

  <div class="form-group">
    <%= form.submit id: "submit", class: "btn btn-primary" %>
  </div>

    
  <% end %>
</div>

app/views/listings/edit.html.erb
<%# this is the edit form for listings, it renders a partial form %>
<h1>Edit Listing</h1>
<p><%= render "form", listing: @listing %></p>

app/views/listings/index.html.erb
<div class="listings-header">
  <div class="logo">
    <%= image_tag "TRADEase.png", alt: "logo", class: "logo" %>
  </div>
</div>

<%#flash message for if an unauthorised user attempts to access a profile improperly %>
<%= flash[:unauthorized] %>

<%# link to make a listing on the homepage %>
<div class="listing-button">
  <%= link_to "make a listing", new_listing_path, class: "btn btn-primary" %>
</div>

<%#note that this is the loop to go through the contents of a listing - additionally note that you don't use IV @listings inside of the loop because of the pipes
so with the image_tag despite using @listing.picture normally, you don't do this here. %>
  <div class="card-container">
  <div class="card-columns">
  <% @listings.each do |listing| %>
    <div class="card" style="width: 25rem;">
      <div class="card-body c-body">
        <h5 class="card-title c-title">Listing</h5>
          <%= image_tag listing.picture, class: "card-img-top" if listing.picture.attached? %>
          <p>Posted by: <%= listing.user.username %></p>
          <p>Listing title: <%= listing.name %></p>
          <p>Estimated budget: <%= listing.price %></p>
          <p>Available? <%= listing.available %></p>
          <%= link_to listing[:name], listing_path(listing[:id]) %>
          <p>Comment Count: <%= listing.comments.count %> </p>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/listings/new.html.erb
<%#this HTML serves only to render the listing form%>
<p><%= render "form", listing: @listing %></p>

app/views/listings/show.html.erb
<h1>Listing:</h1>

<div class="card show-card-container">
  <p>listing: <%= @listing.name %></p>
  <p>price: <%= @listing.price %></p>
  <p>available: <%= @listing.available %></p>
  <p>description: <%= @listing.description %></p>
  <%= image_tag @listing.picture if @listing.picture.attached? %>
</div>

<%# if the current user's listing including the instance variable of the currently shown listing then render the edit and delete %>
<% if user_signed_in? && current_user.listings.include?(@listing) %> 
  <p><%= link_to 'Edit', edit_listing_path %></p>
  <p><%= link_to 'Delete', listing_path, method: :delete %></p>
<% end %>


<%# this is the stripe payment functionality!%>
<button data-stripe="payment", id="stripe">Safe pay</button>
<p>We offer payment facilities and will transfer the funds safely to the other party to the transaction, minus our usage fee</p>

<%# this is how to render the amount of comments on a listing %>
<p>comment count: <%= @listing.comments.count %></p>

<%#this is what renders the comments, collection means use this partial but use for this array of things %>
<div class="comments-container">
  <%= render partial: "comments/comment", collection: @listing.comments %>
</div>

<%#requires a different path as the comment form exists in a different folder (comments), and not listing where the form is displayed%>

<% if current_user.tradesman || @listing.user_id == current_user.id %>
  <div class="new-comment">
    <%= render 'comments/comment_form', comment: @comment %>
  </div>
  <% else %>
    <p><strong>You must be a certified tradie to respond to other people's listings!</strong></p>
<% end %>


<%= javascript_pack_tag "stripe" %>