config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#landing"

  resources :listings do
    resources :comments, only: [:new, :create, :destroy]
  end 
  resources :tradesmen
  resources :profiles do 
    member do
      get "profile_listings"
      end
      resources :reviews, only: [:new, :create, :destroy]
    end
    
  resources :payments, only: [:create]
  get "/payments/success", to: "payments#success"
  get "/payments/cancel", to: "payments#cancel"
  post "/payments/webhook", to: "payments#webhook"

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_nav.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%#below are the lines to log out and return to listings page, I haven't added their class so they default to their container classes parameters %>
          <%= link_to "Listings", listings_path, class: "nav-link custom-class links-hover" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Sign Out", destroy_user_session_path, method: "delete", class: "nav-link custom-class links-hover" %>
        </li>
        <li class="nav-item active">
          <% if current_user.profile.nil? %>
            <%= link_to "Make Your Profile", new_profile_path, class: "nav-link custom class links-hover" %>
          <% end %>
        </li>
        <li class="nav-item active">
            <% unless current_user.profile.nil? %>
              <%= link_to "Your Profile", profile_path(current_user.profile.id), class: "nav-link custom-class links-hover" %>
            <% end %>
        </li>
        <li class="nav-item active">
          <% if current_user.tradesman.nil? %>
            <%= link_to "Become a Tradie!", new_tradesman_path, class: "nav-link custom-class links-hover" %>
          <% end %>
        </li>
        <li class="nav-item active nav-link custom-class">
          <%= form_with(scope: :search, url: listings_path, method: 'get', local: true) do |f| %>
            <%= f.label :listing %>
            <%= f.text_field :listing %>
            <%= f.submit %>
            <%= f.label :min_price %>
            <%= f.number_field :min_price %>
            <%= f.label :max_price %>
            <%= f.number_field :max_price %>
            <%= f.submit %>
          <% end %>
        </li>
        <li class="nav-item active">
          <%= link_to "About Us", root_path, class: "nav-link custom-class links-hover" %>
        </li>
      </ul>
    </div>
  </nav>